version: "3.3"
services:
  main-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digicode-task-tracker
    restart: on-failure
    ports:
      - 4005:8080
    depends-on:
      - postgres
      - pgadmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: postgres-pgadmin4
    restart: "no"
    ports:
      - 80:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=test@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=test
    depends-on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres-db
    restart: "no"
      ports:
        - 5432:5432
      volumes:
        - C:\docker\postgres:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=$$2a$$04$$3didaS2RPv6bt7ZDyNFI2OFuy7J85z089KQV3QwSElsVCKES7Dyr.
        - POSTGRES_DB=postgres